import Header from "./Header/page";
import "./globals.css";
import { Inter } from "next/font/google";
import Provider from "./Components/Provider";
import Providers from "./Redux/Provider";
import Toogle from "./Toogle/page";
import BottomNav from "./BottomNav/page";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  return (
    <html lang="en" className="light h-[100vh]">
      <body className={inter.className}>
        <Providers>
          <Provider>
            <Header></Header>
            <Toogle></Toogle>
            {children}
            <BottomNav></BottomNav>
          </Provider>
        </Providers>
      </body>
    </html>
  );
}
